name: docs
on:
  push:
    branches: ['main']
  pull_request:
permissions: read-all
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: '1.23'
          cache: true
      - run: ./.github/workflows/check-docs.sh
