name: docs
on:
  push:
    branches: ['main']
  pull_request:
permissions: read-all
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.23'
          cache: true
      - run: ./.github/workflows/check-docs.sh
